-- Create the database
CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;

-- Create super_user
CREATE USER IF NOT EXISTS '${MYSQL_SUPER_USER_NAME}'@'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_SUPER_USER_PASSWORD}'
  REQUIRE SUBJECT '${super_user_parsed_subject}' AND ISSUER '${super_user_parsed_issuer}';
GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_SUPER_USER_NAME}'@'%' WITH GRANT OPTION;
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO '${MYSQL_SUPER_USER_NAME}'@'%';
GRANT BINLOG_ADMIN ON *.* TO '${MYSQL_SUPER_USER_NAME}'@'%';
GRANT RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, REPLICATION_SLAVE_ADMIN ON *.* TO '${MYSQL_SUPER_USER_NAME}'@'%';

-- Create read-write user
CREATE USER IF NOT EXISTS '${MYSQL_RW_USER_NAME}'@'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_RW_USER_PASSWORD}'
  REQUIRE SUBJECT '${rw_user_parsed_subject}' AND ISSUER '${rw_user_parsed_issuer}';
GRANT ALL PRIVILEGES ON `${MYSQL_DATABASE}`.* TO '${MYSQL_RW_USER_NAME}'@'%';

-- Create read-only user
CREATE USER IF NOT EXISTS '${MYSQL_RO_USER_NAME}'@'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_RO_USER_PASSWORD}'
  REQUIRE SUBJECT '${ro_user_parsed_subject}' AND ISSUER '${ro_user_parsed_issuer}';
GRANT SELECT ON `${MYSQL_DATABASE}`.* TO '${MYSQL_RO_USER_NAME}'@'%';

-- Finalize
FLUSH PRIVILEGES;
