STOP REPLICA;
RESET REPLICA ALL;

CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='${MYSQL_MASTER_HOST_NAME}',
  SOURCE_USER='${MYSQL_SUPER_USER_NAME}',
  SOURCE_PASSWORD='${MYSQL_SUPER_USER_PASSWORD}',
  SOURCE_AUTO_POSITION=1,
  SOURCE_SSL=1,
  SOURCE_SSL_CA='/etc/ssl/certs/mysql/clients/${MYSQL_SUPER_USER_NAME}/ca.pem',
  SOURCE_SSL_CERT='/etc/ssl/certs/mysql/clients/${MYSQL_SUPER_USER_NAME}/leaf.pem',
  SOURCE_SSL_KEY='/etc/ssl/certs/mysql/clients/${MYSQL_SUPER_USER_NAME}/key.pem';

START REPLICA;
